{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import datetime\n",
    "import os\n",
    "from sqlalchemy import create_engine\n",
    "import pandas_gbq\n",
    "import requests\n",
    "import json\n",
    "import pandas\n",
    "from oauth2client.service_account import ServiceAccountCredentials\n",
    "from google.oauth2 import service_account\n",
    "import gspread\n",
    "import string\n",
    "import pandas as pd\n",
    "from ga_connector import ga_connect\n",
    "from pandas import DataFrame as df\n",
    "from googleapiclient.discovery import build"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "key_path = 'C:\\\\Users\\\\messnerav\\\\projects\\\\m2-main-cd9ed0b4e222.json'\n",
    "gbq_credential = service_account.Credentials.from_service_account_file(key_path,)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sheet_ready(df_r):\n",
    "    rows  = [list(df_r.columns)]\n",
    "    for i in df_r.itertuples():\n",
    "        ls=list(i)[1:]\n",
    "        rows.append(ls)\n",
    "    return rows\n",
    "\n",
    "def date_pairs(date1, date2, step= 1):\n",
    "    pairs= []\n",
    "    while date2 >= date1:\n",
    "        prev_date = date2 - datetime.timedelta(days=step-1) if date2 - datetime.timedelta(days=step) >= date1 else date1\n",
    "        pair = [str(prev_date), str(date2)]   \n",
    "        date2 -= datetime.timedelta(days=step)\n",
    "        pairs.append(pair)\n",
    "    pairs.reverse()\n",
    "    return pairs\n",
    "\n",
    "def get_cpc_soures(cpms):\n",
    "    if 'second' in cpms:\n",
    "        return 'УП реклама'\n",
    "    if 'new-building' in cpms:\n",
    "        return 'Новосторойки реклама'\n",
    "    if cpms == '(not set)':\n",
    "        return 'Не рекламные'\n",
    "    else:\n",
    "        return 'Другие рекламные кампании'\n",
    "    \n",
    "def get_location(s):\n",
    "    if 'serp' in s.lower():\n",
    "        return 'SERP'\n",
    "    if 'card' in s.lower():\n",
    "        return 'CARD'\n",
    "    else:\n",
    "        return None \n",
    "    \n",
    "def get_high(s):\n",
    "    if 'bottom' in s.lower():\n",
    "        return 'bottom'\n",
    "    if 'top' in s.lower():\n",
    "        return 'top'\n",
    "    else:\n",
    "        return None     \n",
    "\n",
    "def get_geo(page):\n",
    "    \n",
    "    msk='moskva-i-oblast|moskva|moskovskaya-oblast'.split('|')\n",
    "    spb= 'sankt-peterburg|leningradskaya-oblast|sankt-peterburg-i-oblast'.split('|')\n",
    "    for g in msk:\n",
    "        if g in page:\n",
    "            return \"MSK\"\n",
    "    for g in spb:\n",
    "        if g in page:\n",
    "            return \"SPB\"\n",
    "        \n",
    "def purify_df(df):\n",
    "    df.columns = [i.replace('ga:', '') for i in cl_calls_df.columns]\n",
    "    df = df[df['eventlabel'].apply(lambda x: 'Rent' not in x)]\n",
    "    df['source'] = df['sourcemedium'].apply(lambda x: x.split(\" / \")[0])\n",
    "    df['medium'] = df['sourcemedium'].apply(lambda x: x.split(\" / \")[1])\n",
    "    df['cpc_type'] = df['campaign'].apply(get_cpc_soures)\n",
    "    df['VAS_type'] = df['eventlabel'].apply(lambda x: \"VAS\" if 'vas' in x.lower() else \"NOT_VAS\")\n",
    "    df['CARD_SERP'] = df['eventlabel'].apply(get_location)\n",
    "    df['TOP_BOTTOM'] = df['eventlabel'].apply(get_high)\n",
    "    df['city'] = df['pagepath'].apply(get_geo)\n",
    "    df['week'] = df['date'].apply(lambda x: x.isocalendar()[1])\n",
    "    df = df.drop(columns = ['sourcemedium','pagepath'])\n",
    "    df['totalEvents'] = df['totalEvents'].astype(int)\n",
    "    df['uniqueEvents'] = df['uniqueEvents'].astype(int)\n",
    "    \n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Downloading: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.33rows/s]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "datetime.date(2021, 10, 18)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "q = \"\"\"SELECT  MAX(DATE) as date FROM `m2-main.UA_REPORTS.A3` \"\"\"\n",
    "\n",
    "last_dt1 = pandas_gbq.read_gbq(q, project_id='m2-main', credentials=gbq_credential)\n",
    "last_dt1 = (datetime.datetime.strptime(last_dt1['date'][0],\"%Y-%m-%d\").date()+datetime.timedelta(days=1))     \n",
    "last_dt1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'startDate': '2021-10-18', 'endDate': '2021-10-20'}\n",
      "{'reportRequests': [{'samplingLevel': 'LARGE', 'viewId': '208464364', 'dateRanges': [{'startDate': '2021-10-18', 'endDate': '2021-10-20'}], 'metrics': [[{'expression': 'ga:totalEvents'}, {'expression': 'ga:uniqueEvents'}]], 'dimensions': [[{'name': 'ga:date'}, {'name': 'ga:eventlabel'}, {'name': 'ga:campaign'}, {'name': 'ga:sourcemedium'}, {'name': 'ga:pagepath'}, {'name': 'ga:deviceCategory'}]], 'pageToken': '0', 'pageSize': '10000', 'filtersExpression': 'ga:eventlabel=~^Cl.*PhoneClick.*'}]}\n",
      "Golden data\n",
      "8188\n",
      "{'startDate': '2021-10-21', 'endDate': '2021-10-24'}\n",
      "{'reportRequests': [{'samplingLevel': 'LARGE', 'viewId': '208464364', 'dateRanges': [{'startDate': '2021-10-21', 'endDate': '2021-10-24'}], 'metrics': [[{'expression': 'ga:totalEvents'}, {'expression': 'ga:uniqueEvents'}]], 'dimensions': [[{'name': 'ga:date'}, {'name': 'ga:eventlabel'}, {'name': 'ga:campaign'}, {'name': 'ga:sourcemedium'}, {'name': 'ga:pagepath'}, {'name': 'ga:deviceCategory'}]], 'pageToken': '0', 'pageSize': '10000', 'filtersExpression': 'ga:eventlabel=~^Cl.*PhoneClick.*'}]}\n",
      "Warning\n",
      "10954\n",
      "10954\n",
      "{'reportRequests': [{'samplingLevel': 'LARGE', 'viewId': '208464364', 'dateRanges': [{'startDate': '2021-10-21', 'endDate': '2021-10-24'}], 'metrics': [[{'expression': 'ga:totalEvents'}, {'expression': 'ga:uniqueEvents'}]], 'dimensions': [[{'name': 'ga:date'}, {'name': 'ga:eventlabel'}, {'name': 'ga:campaign'}, {'name': 'ga:sourcemedium'}, {'name': 'ga:pagepath'}, {'name': 'ga:deviceCategory'}]], 'pageToken': '10000', 'pageSize': '10000', 'filtersExpression': 'ga:eventlabel=~^Cl.*PhoneClick.*'}]}\n",
      "Warning\n",
      "19142\n"
     ]
    }
   ],
   "source": [
    "date1 = last_dt1\n",
    "end = (datetime.datetime.today() -datetime.timedelta(days=1)).date()\n",
    "dates_couples = date_pairs(date1,end, step=4)\n",
    "    \n",
    "\n",
    "ga_conc = ga_connect('208464364')\n",
    "\n",
    "filtr = 'ga:eventlabel=~^Cl.*PhoneClick.*'\n",
    "\n",
    "\n",
    "params = {'dimetions':  [{'name': 'ga:date'},\n",
    "                         {'name': 'ga:eventlabel'},\n",
    "                         {'name': 'ga:campaign'},\n",
    "                         {'name': 'ga:sourcemedium'},\n",
    "                         {'name': 'ga:pagepath'},\n",
    "                         {'name': 'ga:deviceCategory'},\n",
    "                         \n",
    "                         \n",
    "                         \n",
    "                        ],\n",
    "        'metrics':[{'expression': 'ga:totalEvents'},\n",
    "                   {'expression': 'ga:uniqueEvents'}\n",
    "                  ],\n",
    "        \n",
    "        'filters': filtr\n",
    "        }\n",
    "\n",
    "\n",
    "cl_calls_df = ga_conc.report_pd(dates_couples,params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>eventlabel</th>\n",
       "      <th>campaign</th>\n",
       "      <th>sourcemedium</th>\n",
       "      <th>pagepath</th>\n",
       "      <th>deviceCategory</th>\n",
       "      <th>totalEvents</th>\n",
       "      <th>uniqueEvents</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>yandex.ru / organic</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-1-ko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>yandex.ru / organic</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-3-ko...</td>\n",
       "      <td>desktop</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_4...</td>\n",
       "      <td>google / cpc</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-4-ko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_5...</td>\n",
       "      <td>google / cpc</td>\n",
       "      <td>/sankt-peterburg/nedvizhimost/prodazha-mnogoko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_c...</td>\n",
       "      <td>google / cpc</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-1-ko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19137</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>yandex / cpc</td>\n",
       "      <td>/moskva/nedvizhimost/prodazha-2-komnatnoi-kvar...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19138</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>yandex / cpc</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-2-ko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19139</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>yandex / cpc</td>\n",
       "      <td>/moskovskaya-oblast/nedvizhimost/prodazha-3-ko...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19140</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>yandex / cpc</td>\n",
       "      <td>/sankt-peterburg/nedvizhimost/prodazha-1-komna...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19141</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>yandex / cpc</td>\n",
       "      <td>/sankt-peterburg/nedvizhimost/prodazha-3-komna...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>19142 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             date                  eventlabel  \\\n",
       "0      2021-10-18    ClCallbackphoneClickShow   \n",
       "1      2021-10-18    ClCallbackphoneClickShow   \n",
       "2      2021-10-18    ClCallbackphoneClickShow   \n",
       "3      2021-10-18    ClCallbackphoneClickShow   \n",
       "4      2021-10-18    ClCallbackphoneClickShow   \n",
       "...           ...                         ...   \n",
       "19137  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19138  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19139  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19140  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19141  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "\n",
       "                                                campaign         sourcemedium  \\\n",
       "0                                              (not set)  yandex.ru / organic   \n",
       "1                                              (not set)  yandex.ru / organic   \n",
       "2      M2_context_google_cpc_search_second-building_4...         google / cpc   \n",
       "3      M2_context_google_cpc_search_second-building_5...         google / cpc   \n",
       "4      M2_context_google_cpc_search_second-building_c...         google / cpc   \n",
       "...                                                  ...                  ...   \n",
       "19137  M2_context_yandex_cpc_network_second-building_...         yandex / cpc   \n",
       "19138  M2_context_yandex_cpc_network_second-building_...         yandex / cpc   \n",
       "19139  M2_context_yandex_cpc_network_second-building_...         yandex / cpc   \n",
       "19140  M2_context_yandex_cpc_network_second-building_...         yandex / cpc   \n",
       "19141  M2_context_yandex_cpc_network_second-building_...         yandex / cpc   \n",
       "\n",
       "                                                pagepath deviceCategory  \\\n",
       "0      /moskovskaya-oblast/nedvizhimost/prodazha-1-ko...         mobile   \n",
       "1      /moskovskaya-oblast/nedvizhimost/prodazha-3-ko...        desktop   \n",
       "2      /moskovskaya-oblast/nedvizhimost/prodazha-4-ko...         mobile   \n",
       "3      /sankt-peterburg/nedvizhimost/prodazha-mnogoko...         mobile   \n",
       "4      /moskovskaya-oblast/nedvizhimost/prodazha-1-ko...         mobile   \n",
       "...                                                  ...            ...   \n",
       "19137  /moskva/nedvizhimost/prodazha-2-komnatnoi-kvar...         mobile   \n",
       "19138  /moskovskaya-oblast/nedvizhimost/prodazha-2-ko...         mobile   \n",
       "19139  /moskovskaya-oblast/nedvizhimost/prodazha-3-ko...         mobile   \n",
       "19140  /sankt-peterburg/nedvizhimost/prodazha-1-komna...         mobile   \n",
       "19141  /sankt-peterburg/nedvizhimost/prodazha-3-komna...         mobile   \n",
       "\n",
       "       totalEvents  uniqueEvents  \n",
       "0                1             1  \n",
       "1                1             1  \n",
       "2                1             1  \n",
       "3                1             1  \n",
       "4                1             1  \n",
       "...            ...           ...  \n",
       "19137            1             1  \n",
       "19138            1             1  \n",
       "19139            1             1  \n",
       "19140            1             1  \n",
       "19141            1             1  \n",
       "\n",
       "[19142 rows x 8 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cl_calls_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-cf39cb898bc0>:58: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['source'] = df['sourcemedium'].apply(lambda x: x.split(\" / \")[0])\n",
      "<ipython-input-3-cf39cb898bc0>:59: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['medium'] = df['sourcemedium'].apply(lambda x: x.split(\" / \")[1])\n",
      "<ipython-input-3-cf39cb898bc0>:60: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['cpc_type'] = df['campaign'].apply(get_cpc_soures)\n",
      "<ipython-input-3-cf39cb898bc0>:61: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['VAS_type'] = df['eventlabel'].apply(lambda x: \"VAS\" if 'vas' in x.lower() else \"NOT_VAS\")\n",
      "<ipython-input-3-cf39cb898bc0>:62: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['CARD_SERP'] = df['eventlabel'].apply(get_location)\n",
      "<ipython-input-3-cf39cb898bc0>:63: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['TOP_BOTTOM'] = df['eventlabel'].apply(get_high)\n",
      "<ipython-input-3-cf39cb898bc0>:64: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['city'] = df['pagepath'].apply(get_geo)\n",
      "<ipython-input-3-cf39cb898bc0>:65: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['week'] = df['date'].apply(lambda x: x.isocalendar()[1])\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>eventlabel</th>\n",
       "      <th>campaign</th>\n",
       "      <th>deviceCategory</th>\n",
       "      <th>totalEvents</th>\n",
       "      <th>uniqueEvents</th>\n",
       "      <th>source</th>\n",
       "      <th>medium</th>\n",
       "      <th>cpc_type</th>\n",
       "      <th>VAS_type</th>\n",
       "      <th>CARD_SERP</th>\n",
       "      <th>TOP_BOTTOM</th>\n",
       "      <th>city</th>\n",
       "      <th>week</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>desktop</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_4...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_5...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_c...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19137</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19138</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19139</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19140</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19141</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>18821 rows × 14 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             date                  eventlabel  \\\n",
       "0      2021-10-18    ClCallbackphoneClickShow   \n",
       "1      2021-10-18    ClCallbackphoneClickShow   \n",
       "2      2021-10-18    ClCallbackphoneClickShow   \n",
       "3      2021-10-18    ClCallbackphoneClickShow   \n",
       "4      2021-10-18    ClCallbackphoneClickShow   \n",
       "...           ...                         ...   \n",
       "19137  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19138  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19139  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19140  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "19141  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "\n",
       "                                                campaign deviceCategory  \\\n",
       "0                                              (not set)         mobile   \n",
       "1                                              (not set)        desktop   \n",
       "2      M2_context_google_cpc_search_second-building_4...         mobile   \n",
       "3      M2_context_google_cpc_search_second-building_5...         mobile   \n",
       "4      M2_context_google_cpc_search_second-building_c...         mobile   \n",
       "...                                                  ...            ...   \n",
       "19137  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "19138  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "19139  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "19140  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "19141  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "\n",
       "       totalEvents  uniqueEvents     source   medium      cpc_type VAS_type  \\\n",
       "0                1             1  yandex.ru  organic  Не рекламные  NOT_VAS   \n",
       "1                1             1  yandex.ru  organic  Не рекламные  NOT_VAS   \n",
       "2                1             1     google      cpc    УП реклама  NOT_VAS   \n",
       "3                1             1     google      cpc    УП реклама  NOT_VAS   \n",
       "4                1             1     google      cpc    УП реклама  NOT_VAS   \n",
       "...            ...           ...        ...      ...           ...      ...   \n",
       "19137            1             1     yandex      cpc    УП реклама      VAS   \n",
       "19138            1             1     yandex      cpc    УП реклама      VAS   \n",
       "19139            1             1     yandex      cpc    УП реклама      VAS   \n",
       "19140            1             1     yandex      cpc    УП реклама      VAS   \n",
       "19141            1             1     yandex      cpc    УП реклама      VAS   \n",
       "\n",
       "      CARD_SERP TOP_BOTTOM city  week  \n",
       "0          None       None  MSK    42  \n",
       "1          None       None  MSK    42  \n",
       "2          None       None  MSK    42  \n",
       "3          None       None  SPB    42  \n",
       "4          None       None  MSK    42  \n",
       "...         ...        ...  ...   ...  \n",
       "19137      None       None  MSK    42  \n",
       "19138      None       None  MSK    42  \n",
       "19139      None       None  MSK    42  \n",
       "19140      None       None  SPB    42  \n",
       "19141      None       None  SPB    42  \n",
       "\n",
       "[18821 rows x 14 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pure_df = purify_df(cl_calls_df)\n",
    "pure_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine('sqlite://')\n",
    "pure_df.to_sql(\"nbs\", con=engine, if_exists = 'replace', index = False)\n",
    "\n",
    "def get_df(query, engine = engine):\n",
    "    df_check = engine.execute(query)\n",
    "    return df(df_check.fetchall(), columns = df_check.keys()).fillna(0)\n",
    "\n",
    "q = '''\n",
    "select \n",
    "    date(date) as date , eventlabel, campaign, deviceCategory, source, medium, cpc_type, VAS_type, \n",
    "    CARD_SERP, TOP_BOTTOM, city, week,\n",
    "    sum(totalEvents) as totalEvents,\n",
    "    sum(uniqueEvents) as uniqueEvents\n",
    "from nbs\n",
    "group by 1,2,3,4,5,6,7,8,9,10,11,12\n",
    "'''\n",
    "hlops = get_df(q)\n",
    "engine.dispose()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>eventlabel</th>\n",
       "      <th>campaign</th>\n",
       "      <th>deviceCategory</th>\n",
       "      <th>source</th>\n",
       "      <th>medium</th>\n",
       "      <th>cpc_type</th>\n",
       "      <th>VAS_type</th>\n",
       "      <th>CARD_SERP</th>\n",
       "      <th>TOP_BOTTOM</th>\n",
       "      <th>city</th>\n",
       "      <th>week</th>\n",
       "      <th>totalEvents</th>\n",
       "      <th>uniqueEvents</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>desktop</td>\n",
       "      <td>yandex.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>(not set)</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_4...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_5...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2021-10-18</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>M2_context_google_cpc_search_second-building_c...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4956</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4957</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4958</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>MSK</td>\n",
       "      <td>42</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4959</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4960</th>\n",
       "      <td>2021-10-24</td>\n",
       "      <td>ClСardSimilarVasPhoneClick</td>\n",
       "      <td>M2_context_yandex_cpc_network_second-building_...</td>\n",
       "      <td>mobile</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>SPB</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4961 rows × 14 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            date                  eventlabel  \\\n",
       "0     2021-10-18    ClCallbackphoneClickShow   \n",
       "1     2021-10-18    ClCallbackphoneClickShow   \n",
       "2     2021-10-18    ClCallbackphoneClickShow   \n",
       "3     2021-10-18    ClCallbackphoneClickShow   \n",
       "4     2021-10-18    ClCallbackphoneClickShow   \n",
       "...          ...                         ...   \n",
       "4956  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "4957  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "4958  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "4959  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "4960  2021-10-24  ClСardSimilarVasPhoneClick   \n",
       "\n",
       "                                               campaign deviceCategory  \\\n",
       "0                                             (not set)        desktop   \n",
       "1                                             (not set)         mobile   \n",
       "2     M2_context_google_cpc_search_second-building_4...         mobile   \n",
       "3     M2_context_google_cpc_search_second-building_5...         mobile   \n",
       "4     M2_context_google_cpc_search_second-building_c...         mobile   \n",
       "...                                                 ...            ...   \n",
       "4956  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "4957  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "4958  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "4959  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "4960  M2_context_yandex_cpc_network_second-building_...         mobile   \n",
       "\n",
       "         source   medium      cpc_type VAS_type CARD_SERP TOP_BOTTOM city  \\\n",
       "0     yandex.ru  organic  Не рекламные  NOT_VAS         0          0  MSK   \n",
       "1     yandex.ru  organic  Не рекламные  NOT_VAS         0          0  MSK   \n",
       "2        google      cpc    УП реклама  NOT_VAS         0          0  MSK   \n",
       "3        google      cpc    УП реклама  NOT_VAS         0          0  SPB   \n",
       "4        google      cpc    УП реклама  NOT_VAS         0          0  MSK   \n",
       "...         ...      ...           ...      ...       ...        ...  ...   \n",
       "4956     yandex      cpc    УП реклама      VAS         0          0  MSK   \n",
       "4957     yandex      cpc    УП реклама      VAS         0          0  MSK   \n",
       "4958     yandex      cpc    УП реклама      VAS         0          0  MSK   \n",
       "4959     yandex      cpc    УП реклама      VAS         0          0  SPB   \n",
       "4960     yandex      cpc    УП реклама      VAS         0          0  SPB   \n",
       "\n",
       "      week  totalEvents  uniqueEvents  \n",
       "0       42            1             1  \n",
       "1       42            1             1  \n",
       "2       42            1             1  \n",
       "3       42            1             1  \n",
       "4       42            1             1  \n",
       "...    ...          ...           ...  \n",
       "4956    42            1             1  \n",
       "4957    42            6             6  \n",
       "4958    42            2             2  \n",
       "4959    42            1             1  \n",
       "4960    42            1             1  \n",
       "\n",
       "[4961 rows x 14 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hlops"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "1it [00:04,  4.87s/it]\n"
     ]
    }
   ],
   "source": [
    "hlops.to_gbq(f'UA_REPORTS.A3', project_id='m2-main', if_exists='append', credentials=gbq_credential)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Downloading: 100%|██████████████████████████████████████████████████████████| 29328/29328 [00:02<00:00, 11638.18rows/s]\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>week</th>\n",
       "      <th>city</th>\n",
       "      <th>eventlabel</th>\n",
       "      <th>source</th>\n",
       "      <th>medium</th>\n",
       "      <th>cpc_type</th>\n",
       "      <th>VAS_type</th>\n",
       "      <th>CARD_SERP</th>\n",
       "      <th>TOP_BOTTOM</th>\n",
       "      <th>deviceCategory</th>\n",
       "      <th>tot_event</th>\n",
       "      <th>u_event</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClSellPhoneClick</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>8</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClSellPhoneClick</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>288</td>\n",
       "      <td>174</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClCallbackphoneClickShow</td>\n",
       "      <td>yandex</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>8</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClSellPhoneClick</td>\n",
       "      <td>facebook</td>\n",
       "      <td>cpc</td>\n",
       "      <td>УП реклама</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>99</td>\n",
       "      <td>81</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29323</th>\n",
       "      <td>42</td>\n",
       "      <td>SPB</td>\n",
       "      <td>ClCardSellSecondVasPhoneClickAll</td>\n",
       "      <td>google</td>\n",
       "      <td>cpc</td>\n",
       "      <td>Новосторойки реклама</td>\n",
       "      <td>VAS</td>\n",
       "      <td>CARD</td>\n",
       "      <td>0</td>\n",
       "      <td>desktop</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29324</th>\n",
       "      <td>42</td>\n",
       "      <td>MSK</td>\n",
       "      <td>ClSellPhoneClick</td>\n",
       "      <td>yandex</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>92</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29325</th>\n",
       "      <td>42</td>\n",
       "      <td>SPB</td>\n",
       "      <td>ClSellPhoneClick</td>\n",
       "      <td>(direct)</td>\n",
       "      <td>(none)</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>mobile</td>\n",
       "      <td>81</td>\n",
       "      <td>51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29326</th>\n",
       "      <td>42</td>\n",
       "      <td>SPB</td>\n",
       "      <td>ClSerpSellPhoneClick</td>\n",
       "      <td>go.mail.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>SERP</td>\n",
       "      <td>0</td>\n",
       "      <td>desktop</td>\n",
       "      <td>8</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29327</th>\n",
       "      <td>42</td>\n",
       "      <td>SPB</td>\n",
       "      <td>ClSerpSellSecondPhoneClick</td>\n",
       "      <td>go.mail.ru</td>\n",
       "      <td>organic</td>\n",
       "      <td>Не рекламные</td>\n",
       "      <td>NOT_VAS</td>\n",
       "      <td>SERP</td>\n",
       "      <td>0</td>\n",
       "      <td>desktop</td>\n",
       "      <td>8</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>29328 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       week city                        eventlabel      source   medium  \\\n",
       "0         8  MSK                  ClSellPhoneClick      google      cpc   \n",
       "1         8  MSK          ClCallbackphoneClickShow      google      cpc   \n",
       "2         8  MSK                  ClSellPhoneClick      yandex      cpc   \n",
       "3         8  MSK          ClCallbackphoneClickShow      yandex      cpc   \n",
       "4         8  MSK                  ClSellPhoneClick    facebook      cpc   \n",
       "...     ...  ...                               ...         ...      ...   \n",
       "29323    42  SPB  ClCardSellSecondVasPhoneClickAll      google      cpc   \n",
       "29324    42  MSK                  ClSellPhoneClick      yandex  organic   \n",
       "29325    42  SPB                  ClSellPhoneClick    (direct)   (none)   \n",
       "29326    42  SPB              ClSerpSellPhoneClick  go.mail.ru  organic   \n",
       "29327    42  SPB        ClSerpSellSecondPhoneClick  go.mail.ru  organic   \n",
       "\n",
       "                   cpc_type VAS_type CARD_SERP TOP_BOTTOM deviceCategory  \\\n",
       "0                УП реклама  NOT_VAS         0          0         mobile   \n",
       "1                УП реклама  NOT_VAS         0          0         mobile   \n",
       "2                УП реклама  NOT_VAS         0          0         mobile   \n",
       "3                УП реклама  NOT_VAS         0          0         mobile   \n",
       "4                УП реклама  NOT_VAS         0          0         mobile   \n",
       "...                     ...      ...       ...        ...            ...   \n",
       "29323  Новосторойки реклама      VAS      CARD          0        desktop   \n",
       "29324          Не рекламные  NOT_VAS         0          0         mobile   \n",
       "29325          Не рекламные  NOT_VAS         0          0         mobile   \n",
       "29326          Не рекламные  NOT_VAS      SERP          0        desktop   \n",
       "29327          Не рекламные  NOT_VAS      SERP          0        desktop   \n",
       "\n",
       "       tot_event  u_event  \n",
       "0              2        2  \n",
       "1              1        1  \n",
       "2            288      174  \n",
       "3              2        2  \n",
       "4             99       81  \n",
       "...          ...      ...  \n",
       "29323          4        4  \n",
       "29324         92       68  \n",
       "29325         81       51  \n",
       "29326          8        8  \n",
       "29327          8        8  \n",
       "\n",
       "[29328 rows x 12 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "q = \"\"\"SELECT week, city, eventlabel, source, medium, cpc_type, VAS_type, CARD_SERP, TOP_BOTTOM,deviceCategory, \n",
    "sum(totalEvents) as tot_event, sum(uniqueEvents) as u_event\n",
    "\n",
    "FROM m2-main.UA_REPORTS.A3\n",
    "\n",
    "group by  1,2,3,4,5,6,7,8,9,10\n",
    "order by 1\"\"\"\n",
    "\n",
    "all_clops=pandas_gbq.read_gbq(q, project_id='m2-main', credentials=gbq_credential)\n",
    "all_clops"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'spreadsheetId': '1_wNegqvnbIEigYMK2qPuzoPvx14fVt4Sb2af8i9pdog',\n",
       " 'updatedRange': 'vas_source!A1:L29329',\n",
       " 'updatedRows': 29329,\n",
       " 'updatedColumns': 12,\n",
       " 'updatedCells': 351948}"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "SCOPES = ['https://www.googleapis.com/auth/analytics.readonly',\n",
    "             'https://spreadsheets.google.com/feeds',\n",
    "         'https://www.googleapis.com/auth/drive']\n",
    "credentials = ServiceAccountCredentials.from_json_keyfile_name('m2ru-322008-49d82df3892d.json', SCOPES)\n",
    "gc = gspread.authorize(credentials)\n",
    "\n",
    "all_clops['tot_event'] = all_clops['tot_event'].astype(int)\n",
    "all_clops['u_event'] = all_clops['u_event'].astype(int)\n",
    "\n",
    "sh = gc.open(\"1. РК Траффик 2020/21 Total\")\n",
    "wk = sh.worksheet('All_clpos')\n",
    "\n",
    "g_clop=sheet_ready(all_clops)\n",
    "wk.update('A1',g_clop)\n",
    "\n",
    "sh = gc.open(\"План/Факт Маркетинг по Классифайду (недельный)\")\n",
    "wk = sh.worksheet('vas_source')\n",
    "\n",
    "g_clop=sheet_ready(all_clops)\n",
    "wk.update('A1',g_clop)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
